import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Shell } from "@/components/lesson/Shell";
import { catalogForTrack } from "@/lib/safepath/catalog";
import { CSP_DOMAIN_NAMES, CSP_DOMAIN_WEIGHTS, DOMAIN_SHORT } from "@/lib/safepath/domains";
import { buildWeeks, daysBetween, defaultPlan, planDeadlineStatus, readPlan, writePlan, type PlannerMode, type StudyPlan } from "@/lib/safepath/planner";
import { TrackPicker } from "@/components/lesson/TrackPicker";
import { readSession, type TrackId } from "@/lib/safepath/session";

export const Route = createFileRoute("/plan")({ component: Plan });
const MODE_COPY: Record<PlannerMode, string> = { adaptive: "Blueprint weights first. Heavier domains stay earlier until they are closed.", mix: "All selected domains blend every week instead of finishing one block first.", domain: "True domain blocks. Finish D1, then D2, in the order you set.", choice: "Your sequence and your selected domains only." };
const MODE_META: Record<PlannerMode, { icon: string; label: string }> = { adaptive: { icon: "◈", label: "Adaptive" }, mix: { icon: "⌘", label: "Mixed" }, domain: { icon: "→", label: "Domain blocks" }, choice: { icon: "✦", label: "My choice" } };

function Plan() {
  const [plan, setPlan] = useState<StudyPlan>(defaultPlan());
  const [completed, setCompleted] = useState<number[]>([]);
  const [track, setTrack] = useState<TrackId>(readSession().track);
  useEffect(() => { const session = readSession(); setPlan(readPlan()); setCompleted(session.completed); setTrack(session.track); }, []);
  function save(next: StudyPlan) { writePlan(next); setPlan(next); }
  const weeks = useMemo(() => buildWeeks(plan, track, completed), [plan, track, completed]);
  const days = daysBetween(plan.startDate, plan.examDate);
  const deadline = useMemo(() => planDeadlineStatus(plan, track, completed), [plan, track, completed]);
  const hoursBudget = Math.round(days * plan.dailyHours);
  const hoursNeeded = Math.round(deadline.totalClasses * 1.2);
  function formatDate(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }); }
  function toggleDomain(d: number) { const has = plan.domains.includes(d); const domains = has ? plan.domains.filter((x) => x !== d) : [...plan.domains, d]; save({ ...plan, domains: domains.length ? domains : [d] }); }
  function moveDomain(d: number, dir: -1 | 1) { const domains = [...plan.domains]; const i = domains.indexOf(d); const j = i + dir; if (i < 0 || j < 0 || j >= domains.length) return; [domains[i], domains[j]] = [domains[j]!, domains[i]!]; save({ ...plan, domains }); }

  return <Shell><div className="sp-wrap space-y-8">
    <div className="plan-hero"><div><p className="sp-kicker">Study planner</p><h1 className="sp-title mt-2 text-4xl">Build your CSP study plan.</h1><p className="mt-3 max-w-2xl text-fg-muted">This is your planning workspace: choose your track, set your exam date, select the domains you need, arrange their order, and then follow the generated weekly map.</p></div><div className="plan-hero-badge"><span>PLAN</span><b>{deadline.daysRemaining}</b><small>days to target</small></div></div>
    <section className={`sp-plan-health is-${deadline.status}`} aria-label="Study plan deadline health"><div className="sp-plan-health-main"><div><p className="sp-kicker">Deadline check</p><h2>{deadline.label}</h2><p>{deadline.detail}</p></div><div className="sp-plan-health-date"><b>{formatDate(plan.examDate)}</b><span>exam target</span></div></div><div className="sp-plan-health-track"><span style={{ width: `${deadline.actualPct}%` }} /></div><div className="sp-plan-health-stats"><span><b>{deadline.actualPct}%</b> completed</span><span><b>{deadline.expectedPct}%</b> expected today</span><span><b>{deadline.remainingClasses}</b> classes left</span><span><b>{deadline.requiredClassesPerDay.toFixed(1)}</b> / day needed</span><span><b>{formatDate(deadline.plannedFinishDate)}</b> generated finish</span></div>{deadline.status === "behind" || deadline.status === "plan-too-slow" ? <div className="sp-plan-health-alert">{deadline.status === "behind" ? `You are behind the pace needed for ${formatDate(plan.examDate)}. Increase your study pace or adjust the plan.` : `The generated map currently finishes after ${formatDate(plan.examDate)}. Increase study capacity or change the target.`}</div> : null}</section>
    <div className="plan-steps"><span className="is-active"><b>1</b> Choose track</span><span><b>2</b> Set schedule</span><span><b>3</b> Choose method</span><span><b>4</b> Arrange domains</span><span><b>5</b> Follow map</span></div>
    <section><div className="plan-section-title"><div><p className="sp-kicker">Step 1</p><h2 className="sp-title mt-2 text-2xl">Choose your learning track</h2></div><span>Course material depth</span></div><TrackPicker track={track} onChange={setTrack} /></section>
    <section><div className="plan-section-title"><div><p className="sp-kicker">Step 2</p><h2 className="sp-title mt-2 text-2xl">Set your schedule</h2></div><span>When + how much</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <label className="sp-card p-4 text-sm"><p className="text-fg-subtle">Course start</p><input type="date" className="sp-field mt-2" value={plan.startDate} onChange={(e) => save({ ...plan, startDate: e.target.value })} /></label>
      <label className="sp-card p-4 text-sm"><p className="text-fg-subtle">Exam target</p><input type="date" className="sp-field mt-2" value={plan.examDate} onChange={(e) => save({ ...plan, examDate: e.target.value })} /></label>
      <article className="sp-card p-4"><p className="text-sm text-fg-subtle">Days remaining</p><p className="mt-2 font-serif text-3xl">{deadline.daysRemaining}</p></article>
      <label className="sp-card p-4 text-sm"><p className="text-fg-subtle">Daily study hours</p><input type="number" min={0.5} max={8} step={0.5} className="sp-field mt-2" value={plan.dailyHours} onChange={(e) => save({ ...plan, dailyHours: Number(e.target.value) || 1 })} /></label>
    </div></section>
    {hoursBudget < hoursNeeded ? <p className="rounded-lg border border-warn/40 bg-bg-elevated p-4 text-sm">Pace check: {hoursBudget} scheduled hours is below the estimated {hoursNeeded}-hour workload for your selected plan. Raise daily hours or move the target date.</p> : null}
    <section><div className="plan-section-title"><div><p className="sp-kicker">Step 3</p><h2 className="sp-title mt-2 text-2xl">How do you want to study?</h2></div><span>Planner method</span></div><div className="plan-mode-grid">{(["adaptive","mix","domain","choice"] as const).map((mode) => <button key={mode} type="button" className={`plan-mode-card ${plan.mode === mode ? "is-selected" : ""}`} onClick={() => save({ ...plan, mode })}><span>{MODE_META[mode].icon}</span><div><b>{MODE_META[mode].label}</b><p>{MODE_COPY[mode]}</p></div><i>{plan.mode === mode ? "✓" : ""}</i></button>)}</div></section>
    <section><div className="plan-section-title"><div><p className="sp-kicker">Step 4</p><h2 className="sp-title mt-2 text-2xl">Mind map: choose and order your domains</h2><p className="mt-2 max-w-3xl text-sm text-fg-muted">Think of this as your CSP roadmap. Every card tells you what the domain actually covers, its blueprint weight, class count, and completion status.</p></div><span>{plan.domains.length}/7 selected</span></div>
      <div className="plan-domain-map">{([1,2,3,4,5,6,7] as const).map((d) => { const rows = catalogForTrack(track).filter((row) => row.domain === d); const done = rows.filter((row) => completed.includes(row.id)).length; const selected = plan.domains.includes(d); const position = plan.domains.indexOf(d); return <article key={d} className={`plan-domain-card ${selected ? "is-selected" : ""}`}><div className="plan-domain-head"><span>D{d}</span><em>{CSP_DOMAIN_WEIGHTS[d]}%</em></div><h3>{DOMAIN_SHORT[d]}</h3><p className="plan-domain-name">{CSP_DOMAIN_NAMES[d]}</p><div className="plan-domain-stat"><b>{done}/{rows.length}</b><small>classes complete</small></div><div className="plan-domain-actions">{selected ? <><button type="button" onClick={() => moveDomain(d,-1)} aria-label={`Move D${d} up`}>↑</button><span>#{position + 1}</span><button type="button" onClick={() => moveDomain(d,1)} aria-label={`Move D${d} down`}>↓</button><button type="button" className="remove" onClick={() => toggleDomain(d)}>Remove</button></> : <button type="button" className="add" onClick={() => toggleDomain(d)}>+ Add to plan</button>}</div></article> })}</div>
    </section>
    <section><div className="plan-section-title"><div><p className="sp-kicker">Step 5</p><h2 className="sp-title mt-2 text-2xl">Your weekly study map</h2><p className="mt-2 text-sm text-fg-muted">Follow these class links in order. Close a class to move forward through the map.</p></div><Link to="/studio" className="sp-btn sp-btn-primary">Open class library →</Link></div><div className="grid gap-3">{weeks.slice(0,12).map((week) => <article key={week.week} className="sp-card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono text-xs text-accent">WEEK {week.week}</p><span className="text-xs text-fg-subtle">{week.items.length} classes</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{week.items.map((row) => <Link key={row.id} to="/learn/$id" params={{ id: String(row.id) }} className="plan-week-item"><span>C{row.id} · D{row.domain}</span><b>{row.title}</b></Link>)}</div></article>)}</div>{weeks.length > 12 ? <p className="mt-3 text-sm text-fg-muted">{weeks.length - 12} more weeks are ready. Complete classes to advance.</p> : null}</section>
  </div></Shell>;
}
