import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo } from "react";
import { Shell } from "@/components/lesson/Shell";
import { readSession } from "@/lib/safepath/session";
import { domainScores, scoreCompetency, masteryGate } from "@/lib/safepath/adaptive-engine";
import { CSP_DOMAIN_NAMES } from "@/lib/safepath/domains";

export const Route = createFileRoute("/readiness")({ component: Readiness });

function Readiness() {
  const session = readSession();
  const attempts = session.attempts;
  const states = useMemo(() => scoreCompetency(attempts.map((a) => ({ domain: `D${a.domain}`, topic: a.topic, competency: a.competency, difficulty: a.difficulty, correct: a.correct, responseTimeSeconds: a.responseTimeSeconds, confidence: a.confidence, errorType: a.errorType, attemptedAt: new Date(a.at).toISOString() }))), [attempts]);
  const domains = useMemo(() => domainScores(attempts.filter((a) => a.domain >= 1 && a.domain <= 7).map((a) => ({ domain: `D${a.domain}`, topic: a.topic, difficulty: a.difficulty, correct: a.correct, responseTimeSeconds: a.responseTimeSeconds, confidence: a.confidence, attemptedAt: new Date(a.at).toISOString() }))), [attempts]);
  const gate = useMemo(() => masteryGate(attempts.map((a) => ({ domain: `D${a.domain}`, topic: a.topic, competency: a.competency, difficulty: a.difficulty, correct: a.correct, responseTimeSeconds: a.responseTimeSeconds, confidence: a.confidence, errorType: a.errorType, attemptedAt: new Date(a.at).toISOString() }))), [attempts]);
  const accuracy = attempts.length ? attempts.filter((a) => a.correct).length / attempts.length : 0;
  const recent = attempts.slice(-20);
  const recentAccuracy = recent.length ? recent.filter((a) => a.correct).length / recent.length : 0;
  const cardsDue = session.cardReviews.filter((r) => r.dueAt <= Date.now()).length;
  const readiness = Math.round((accuracy * 0.35 + recentAccuracy * 0.35 + gate.score / 100 * 0.2 + Math.min(1, attempts.length / 100) * 0.1) * 100);
  const level = attempts.length < 10 ? "Building evidence" : readiness >= 85 && gate.mastered ? "Strong evidence" : readiness >= 70 ? "Developing" : "Repair needed";

  return <Shell><div className="sp-wrap max-w-6xl space-y-6"><header><p className="sp-kicker">CSP readiness</p><h1 className="sp-title mt-2 text-4xl">Know where you stand.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-fg-muted">This is a SafePath learning signal, not a BCSP pass prediction. It uses your recorded accuracy, recency, applied evidence and confidence signals; more evidence makes the signal more meaningful.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="sp-card p-5"><div className="text-xs text-fg-muted">Readiness signal</div><div className="mt-1 text-3xl font-semibold">{readiness}%</div><div className="mt-1 text-xs text-fg-muted">{level}</div></div><div className="sp-card p-5"><div className="text-xs text-fg-muted">All-time accuracy</div><div className="mt-1 text-3xl font-semibold">{Math.round(accuracy * 100)}%</div></div><div className="sp-card p-5"><div className="text-xs text-fg-muted">Recent 20</div><div className="mt-1 text-3xl font-semibold">{Math.round(recentAccuracy * 100)}%</div></div><div className="sp-card p-5"><div className="text-xs text-fg-muted">Attempts</div><div className="mt-1 text-3xl font-semibold">{attempts.length}</div></div><div className="sp-card p-5"><div className="text-xs text-fg-muted">Cards due</div><div className="mt-1 text-3xl font-semibold">{cardsDue}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><div className="sp-card p-5"><div className="flex items-end justify-between gap-3"><div><p className="sp-kicker">Blueprint evidence</p><h2 className="mt-1 text-2xl font-semibold">Domain performance</h2></div><Link to="/domains" className="sp-btn sp-btn-ghost">Blueprint →</Link></div><div className="mt-5 space-y-3">{Array.from({ length: 7 }, (_, i) => i + 1).map((d) => { const row = domains.find((x) => x.domain === `D${d}`); const pct = row ? Math.round(row.accuracy * 100) : 0; return <div key={d}><div className="flex justify-between gap-3 text-sm"><span>D{d} · {CSP_DOMAIN_NAMES[d]}</span><span className="font-mono">{row ? `${pct}% · ${row.attempts}` : "No evidence"}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-accent" style={{ width: `${pct}%` }} /></div></div>; })}</div></div>
    <div className="sp-card p-5"><p className="sp-kicker">Next actions</p><h2 className="mt-1 text-2xl font-semibold">Repair before you chase volume</h2><div className="mt-4 space-y-3">{states.slice(0, 4).map((state) => <div key={`${state.domain}-${state.topic}`} className="rounded-lg border border-border p-3"><div className="flex justify-between gap-3 text-sm font-medium"><span>{state.domain} · {state.topic}</span><span>{Math.round(state.masteryScore * 100)}%</span></div><p className="mt-1 text-xs text-fg-muted">{state.recommendedAction} · next difficulty {state.recommendedDifficulty}/5 · {state.attempts} attempts</p></div>)}{!states.length ? <p className="text-sm text-fg-muted">Start a practice set to build your first evidence.</p> : null}</div><div className="mt-5 flex flex-wrap gap-2"><Link to="/practice" className="sp-btn sp-btn-primary">Target practice</Link><Link to="/cards" className="sp-btn sp-btn-ghost">Review cards</Link></div></div></section>
    <section className="sp-card p-5"><h2 className="text-xl font-semibold">Mastery gate</h2><p className="mt-2 text-sm text-fg-muted">SafePath's internal mastery gate looks for distributed, accurate, applied retrieval and reasonable confidence calibration. It is a product learning threshold, not an official BCSP requirement.</p><div className="mt-4 flex flex-wrap items-center gap-4"><span className="rounded-full border px-4 py-2 text-sm font-semibold">{gate.mastered ? "Evidence threshold met" : "Evidence threshold not yet met"}</span><span className="text-sm text-fg-muted">{gate.reason}</span></div></section>
  </div></Shell>;
}
