export type BcspTaskGuide = {
  label: string;
  plain: string;
  targets: string[];
};

/**
 * Current CSP11 blueprint task language translated into learner-friendly words.
 * This is guidance, not an official BCSP course or exam question set.
 */
export const BCSP_TASK_GUIDES: Record<string, BcspTaskGuide> = {
  "CSP-11 D1.01": { label: "Prevention Through Design", plain: "Learn how to remove or reduce hazards while the workplace, equipment, or process is still being designed.", targets: ["Elimination and substitution", "Safer facility, machine, and work design", "Life-cycle thinking"] },
  "CSP-11 D1.02": { label: "Process Safety", plain: "Learn how to keep hazardous processes safe by controlling energy, chemistry, equipment, and process changes.", targets: ["Pressure relief and process safeguards", "Chemical compatibility and materials of construction", "Process flow diagrams and Management of Change"] },
  "CSP-11 D1.03": { label: "Common Workplace Hazards", plain: "Learn how to recognize and evaluate common workplace hazards and choose effective controls.", targets: ["Electrical, falls, confined spaces, LOTO", "Water, caught-in, struck-by, excavation", "Control selection and verification"] },
  "CSP-11 D1.04": { label: "Facility Life Safety", plain: "Learn how building and public-space features protect people during normal use and emergencies.", targets: ["Occupancy and floor loading", "Egress and life-safety features", "Public-space hazards"] },
  "CSP-11 D1.05": { label: "Fleet Safety", plain: "Learn how to manage driver, vehicle, and journey risks before and during driving.", targets: ["Driver and equipment safety", "Fatigue, impairment, and surveillance", "GPS, telematics, fuel and hybrid systems"] },
  "CSP-11 D1.06": { label: "Materials Handling", plain: "Learn how to move people and materials safely using the right equipment, method, and controls.", targets: ["Forklifts and aerial lifts", "Cranes, hoists, rigging, and hand trucks", "Manual handling and drones"] },
  "CSP-11 D1.07": { label: "Tools, Machines, and Equipment", plain: "Learn how to evaluate machines and tools for hazards, safeguards, safe use, and maintenance.", targets: ["Hand and power tools", "Ladders, grinders, hydraulics", "Machine guarding and robotics"] },
  "CSP-11 D2.01": { label: "Benchmarking and Gap Analysis", plain: "Learn how to compare actual performance with a required or desired standard and identify the gaps.", targets: ["Choose a meaningful benchmark", "Measure the current state", "Turn gaps into actions"] },
  "CSP-11 D2.02": { label: "Performance Standards and Action Plans", plain: "Learn how to turn performance requirements into a practical plan with owners, timing, and evidence.", targets: ["Define the required outcome", "Prioritize actions", "Verify completion and effectiveness"] },
  "CSP-11 D2.03": { label: "EHS Culture", plain: "Learn how to measure and improve the behaviors, leadership, trust, and systems that shape safety culture.", targets: ["Use leading evidence, not slogans", "Assess leadership and worker involvement", "Improve culture using measured results"] },
  "CSP-11 D2.04": { label: "Incident Investigation and Corrective Action", plain: "Learn how to find causes and contributing factors, then fix the system instead of only blaming a person.", targets: ["Collect reliable evidence", "Identify root and contributing causes", "Choose and verify corrective actions"] },
  "CSP-11 D2.05": { label: "Management of Change", plain: "Learn how to identify and control new risk before, during, and after a change.", targets: ["Screen and approve changes", "Review hazards and affected people", "Verify the change after implementation"] },
  "CSP-11 D2.06": { label: "System Safety Analysis", plain: "Learn how tools such as FTA, FMEA, Safety Case, and risk summation help understand system failure and risk.", targets: ["Know what each method is for", "Build and interpret the analysis", "Use results to make decisions"] },
  "CSP-11 D2.07": { label: "Leading and Lagging Indicators", plain: "Learn the difference between actions that predict performance and results that show what already happened.", targets: ["Select useful leading measures", "Interpret lagging results", "Avoid measures that reward paperwork only"] },
  "CSP-11 D2.08": { label: "EHS Management and Audit Systems", plain: "Learn the purpose and basic structure of major EHS management and audit standards.", targets: ["ISO 14000 series", "ISO 45001 and ANSI Z10", "ISO 19011 audit principles"] },
  "CSP-11 D2.09": { label: "Plans, Systems, and Policies", plain: "Learn what makes an EHS plan or policy useful, complete, controlled, and connected to requirements.", targets: ["Requirements and standards", "Roles, resources, procedures, and records", "Review and improvement"] },
  "CSP-11 D2.10": { label: "Document Retention and Management", plain: "Learn how to keep, protect, find, control, and dispose of important EHS records correctly.", targets: ["Training, exposure, maintenance, and incident records", "Audit and environmental records", "Privacy, personal information, and trade secrets"] },
  "CSP-11 D2.11": { label: "Budgeting, Finance, and Economics", plain: "Learn how safety decisions affect money, resources, procurement, cost, benefit, and return on investment.", targets: ["Budget and resource planning", "ROI and cost-benefit thinking", "Safety's role in procurement"] },
  "CSP-11 D2.12": { label: "Leadership and Management", plain: "Learn how leadership style, motivation, authority, responsibility, accountability, and communication affect EHS results.", targets: ["Leadership versus management", "Motivation and discipline", "Clear authority, responsibility, and accountability"] },
  "CSP-11 D2.13": { label: "Project Management", plain: "Learn how to organize safety work using scope, people, timing, responsibilities, and deliverables.", targets: ["RACI and ownership", "Timelines and dependencies", "Monitor delivery and close actions"] },
  "CSP-11 D2.14": { label: "EHS Data Analysis", plain: "Learn how to read safety and health data correctly and use it to make better decisions.", targets: ["Mean, median, and mode", "Confidence intervals and probability", "Exposure/release data and Pareto analysis"] },
  "CSP-11 D3.01": { label: "Safety Risk Evaluation", plain: "Learn the full risk cycle: identify, analyze, evaluate, treat, monitor, and communicate risk.", targets: ["Identify hazards and consequences", "Evaluate likelihood and severity", "Monitor and communicate changing risk"] },
  "CSP-11 D3.02": { label: "EHS Risk Management", plain: "Learn how to use risk-analysis methods to identify hazards and select controls.", targets: ["Risk analysis and ranking", "JHA and PHA", "Hierarchy of controls"] },
  "CSP-11 D3.03": { label: "Financial Risk Mitigation", plain: "Learn the difference between avoiding, retaining, sharing, transferring, preventing, and reducing financial risk.", targets: ["Risk avoidance and retention", "Risk sharing and transfer", "Loss prevention versus loss reduction"] },
  "CSP-11 D3.04": { label: "Risk Analysis and Monitoring", plain: "Learn how to identify, rank, and monitor risks across emergencies, fire, health, hazardous materials, and environmental compliance.", targets: ["Risk ranking", "Control and preparedness", "Ongoing monitoring"] },
  "CSP-11 D4.01": { label: "Emergency Response Plans", plain: "Learn how to create, use, test, maintain, and improve an Emergency Response Plan.", targets: ["Fire, severe weather, spills, utilities, cyber events", "Roles, communication, evacuation, and resources", "Exercises, review, and maintenance"] },
  "CSP-11 D4.02": { label: "Disaster Response and Recovery", plain: "Learn how organizations coordinate during a disaster and restore critical operations afterward.", targets: ["Incident command", "Business continuity and contingency planning", "Recovery priorities"] },
  "CSP-11 D4.03": { label: "Fire Prevention, Protection, and Suppression", plain: "Learn the basic systems and practices used to prevent fires, protect occupants, and suppress fires.", targets: ["Fire prevention", "Detection and protection systems", "Suppression and response"] },
  "CSP-11 D4.04": { label: "Hazardous Materials Transportation and Security", plain: "Learn how hazardous materials are prepared, transported, secured, and managed safely.", targets: ["Classification and shipping controls", "Packaging, labeling, and documentation", "Security and emergency information"] },
  "CSP-11 D4.05": { label: "Workplace Violence Prevention", plain: "Learn how to recognize, prevent, prepare for, and respond to workplace violence risks.", targets: ["Threat identification", "Prevention and reporting", "Response and recovery"] },
  "CSP-11 D5.01": { label: "Environmental Protection and Pollution Prevention", plain: "Learn how to prevent releases and reduce pollution at the source.", targets: ["Spill prevention and containment", "Abatement and good practices", "Source control and verification"] },
  "CSP-11 D5.02": { label: "Hazardous Materials Management", plain: "Learn how hazardous materials are classified, stored, handled, secured, and disposed of.", targets: ["GHS classification", "Storage and handling", "Hazardous-waste management"] },
  "CSP-11 D5.03": { label: "Waste Management", plain: "Learn how to manage universal waste, recycling, spill cleanup, labeling, and remediation correctly.", targets: ["Identify and segregate waste", "Label, store, and transport safely", "Cleanup and remediation"] },
  "CSP-11 D5.04": { label: "Sustainability", plain: "Learn how environmental performance can be improved by reducing resource use and considering the whole supply chain.", targets: ["Reduce, reuse, recycle", "Resource efficiency", "Supply-chain thinking"] },
  "CSP-11 D5.05": { label: "Environmental Issues", plain: "Learn how major environmental issues can affect people, assets, compliance, and business decisions.", targets: ["Aging infrastructure and asbestos", "Air pollution and climate change", "ESG considerations"] },
  "CSP-11 D6.01": { label: "Occupational Exposure Assessment", plain: "Learn how to anticipate, recognize, evaluate, and control workplace exposures using sound sampling and measurement.", targets: ["Sampling strategy and instruments", "Chemicals, noise, radiation, heat/cold, ventilation", "Silica, dust, hot work, lasers and other exposures"] },
  "CSP-11 D6.02": { label: "Public Health and Epidemiology", plain: "Learn how disease patterns, risk factors, rates, and statistics help safety professionals understand population health.", targets: ["Incidence and prevalence", "Risk factors and infectious disease", "Interpret health statistics"] },
  "CSP-11 D6.03": { label: "Toxicology and Exposure Controls", plain: "Learn how a substance can affect the body and how exposure information guides controls.", targets: ["Dose and response", "LD50, LC50 and toxic effects", "Exposure-control and risk-mitigation plans"] },
  "CSP-11 D6.04": { label: "Ergonomics and Human Factors", plain: "Learn how work design, human abilities, body mechanics, and fatigue affect injury and performance.", targets: ["Anthropometrics and visual ability", "Lifting and body mechanics", "Vibration and fatigue"] },
  "CSP-11 D6.05": { label: "Chemistry and Containment Calculations", plain: "Learn how to use basic chemistry and volume calculations to size containment and manage hazardous-material storage.", targets: ["Chemical properties and compatibility", "Containment volume", "Storage requirements and calculations"] },
  "CSP-11 D6.06": { label: "Physics", plain: "Learn the physics needed to understand safety problems involving energy, weight, force, motion, and stress.", targets: ["Forms of energy", "Force, weight, and motion", "Stress and applied calculations"] },
  "CSP-11 D7.01": { label: "Training Needs Assessment", plain: "Learn how to determine what workers actually need to know, do, and prove before selecting training.", targets: ["Competency and qualification gaps", "Target audience and job needs", "Decide whether training is the right solution"] },
  "CSP-11 D7.02": { label: "Training Program Design", plain: "Learn how to build training that matches the job, learner, content, delivery method, and learning needs.", targets: ["Objectives and materials", "Different learning preferences", "Presentation methods and tools"] },
  "CSP-11 D7.03": { label: "Continuous Improvement in Training", plain: "Learn how to use feedback and performance results to improve a training program over time.", targets: ["Plan, deliver, check, improve", "Use evidence from performance", "Update content and delivery"] },
  "CSP-11 D7.04": { label: "Training Effectiveness", plain: "Learn how to prove whether training changed knowledge, behavior, and job performance.", targets: ["Assessments and demonstrations", "On-the-job performance and compliance", "Feedback and improvement"] },
  "CSP-11 D7.05": { label: "Training Methods and Technology", plain: "Learn when to use classroom, online, simulation, computer-based learning, coaching, OJT, and AI-supported methods.", targets: ["Choose method for the objective", "Engagement and practice", "AI and technology used responsibly"] },
  "CSP-11 D7.06": { label: "Adult Learning", plain: "Learn how adults learn best and how to design training that respects experience, relevance, practice, and different ways of learning.", targets: ["Relevant and practical content", "Active practice and feedback", "Visual, auditory, reading/writing, and kinesthetic approaches"] },
};

export function guideForTask(taskCode: string): BcspTaskGuide | null {
  return BCSP_TASK_GUIDES[taskCode] ?? null;
}
