/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as BankRouteImport } from './routes/bank'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ErgoRouteImport } from './routes/ergo'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ExamDayRouteImport } from './routes/exam-day'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MathRouteImport } from './routes/math'
import { Route as MockRouteImport } from './routes/mock'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ToxRouteImport } from './routes/tox'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as AssessPostRouteImport } from './routes/assess.post'
import { Route as AssessPreRouteImport } from './routes/assess.pre'
import { Route as AssessSelfRouteImport } from './routes/assess.self'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnIdRouteImport } from './routes/learn.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgoRoute = ErgoRouteImport.update({
  id: '/ergo',
  path: '/ergo',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamDayRoute = ExamDayRouteImport.update({
  id: '/exam-day',
  path: '/exam-day',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ToxRoute = ToxRouteImport.update({
  id: '/tox',
  path: '/tox',
  getParentRoute: () => rootRouteImport,
} as any)
const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessPostRoute = AssessPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AssessRoute,
} as any)
const AssessPreRoute = AssessPreRouteImport.update({
  id: '/pre',
  path: '/pre',
  getParentRoute: () => AssessRoute,
} as any)
const AssessSelfRoute = AssessSelfRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => AssessRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIdRoute = LearnIdRouteImport.update({
  id: '/learn/$id',
  path: '/learn/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/assess': typeof AssessRouteWithChildren
  '/bank': typeof BankRoute
  '/blueprint': typeof BlueprintRoute
  '/calculator': typeof CalculatorRoute
  '/cards': typeof CardsRoute
  '/certificate': typeof CertificateRoute
  '/challenge': typeof ChallengeRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/domains': typeof DomainsRoute
  '/drill': typeof DrillRoute
  '/eligibility': typeof EligibilityRoute
  '/ergo': typeof ErgoRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/exam-day': typeof ExamDayRoute
  '/flags': typeof FlagsRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/ready': typeof ReadyRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/tox': typeof ToxRoute
  '/warmup': typeof WarmupRoute
  '/assess/post': typeof AssessPostRoute
  '/assess/pre': typeof AssessPreRoute
  '/assess/self': typeof AssessSelfRoute
  '/learn/$id': typeof LearnIdRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/assess': typeof AssessRouteWithChildren
  '/bank': typeof BankRoute
  '/blueprint': typeof BlueprintRoute
  '/calculator': typeof CalculatorRoute
  '/cards': typeof CardsRoute
  '/certificate': typeof CertificateRoute
  '/challenge': typeof ChallengeRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/domains': typeof DomainsRoute
  '/drill': typeof DrillRoute
  '/eligibility': typeof EligibilityRoute
  '/ergo': typeof ErgoRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/exam-day': typeof ExamDayRoute
  '/flags': typeof FlagsRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/ready': typeof ReadyRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/tox': typeof ToxRoute
  '/warmup': typeof WarmupRoute
  '/assess/post': typeof AssessPostRoute
  '/assess/pre': typeof AssessPreRoute
  '/assess/self': typeof AssessSelfRoute
  '/learn/$id': typeof LearnIdRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/assess': typeof AssessRouteWithChildren
  '/bank': typeof BankRoute
  '/blueprint': typeof BlueprintRoute
  '/calculator': typeof CalculatorRoute
  '/cards': typeof CardsRoute
  '/certificate': typeof CertificateRoute
  '/challenge': typeof ChallengeRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/domains': typeof DomainsRoute
  '/drill': typeof DrillRoute
  '/eligibility': typeof EligibilityRoute
  '/ergo': typeof ErgoRoute
  '/errors': typeof ErrorsRoute
  '/exam': typeof ExamRoute
  '/exam-day': typeof ExamDayRoute
  '/flags': typeof FlagsRoute
  '/formulas': typeof FormulasRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/math': typeof MathRoute
  '/mock': typeof MockRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/ready': typeof ReadyRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/tox': typeof ToxRoute
  '/warmup': typeof WarmupRoute
  '/assess/post': typeof AssessPostRoute
  '/assess/pre': typeof AssessPreRoute
  '/assess/self': typeof AssessSelfRoute
  '/learn/$id': typeof LearnIdRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/assess'
    | '/bank'
    | '/blueprint'
    | '/calculator'
    | '/cards'
    | '/certificate'
    | '/challenge'
    | '/coach'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/domains'
    | '/drill'
    | '/eligibility'
    | '/ergo'
    | '/errors'
    | '/exam'
    | '/exam-day'
    | '/flags'
    | '/formulas'
    | '/games'
    | '/library'
    | '/login'
    | '/math'
    | '/mock'
    | '/onboarding'
    | '/plan'
    | '/practice'
    | '/ready'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/studio'
    | '/today'
    | '/topics'
    | '/tox'
    | '/warmup'
    | '/assess/post'
    | '/assess/pre'
    | '/assess/self'
    | '/learn/$id'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/assess'
    | '/bank'
    | '/blueprint'
    | '/calculator'
    | '/cards'
    | '/certificate'
    | '/challenge'
    | '/coach'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/domains'
    | '/drill'
    | '/eligibility'
    | '/ergo'
    | '/errors'
    | '/exam'
    | '/exam-day'
    | '/flags'
    | '/formulas'
    | '/games'
    | '/library'
    | '/login'
    | '/math'
    | '/mock'
    | '/onboarding'
    | '/plan'
    | '/practice'
    | '/ready'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/studio'
    | '/today'
    | '/topics'
    | '/tox'
    | '/warmup'
    | '/assess/post'
    | '/assess/pre'
    | '/assess/self'
    | '/learn/$id'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/assess'
    | '/bank'
    | '/blueprint'
    | '/calculator'
    | '/cards'
    | '/certificate'
    | '/challenge'
    | '/coach'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/domains'
    | '/drill'
    | '/eligibility'
    | '/ergo'
    | '/errors'
    | '/exam'
    | '/exam-day'
    | '/flags'
    | '/formulas'
    | '/games'
    | '/library'
    | '/login'
    | '/math'
    | '/mock'
    | '/onboarding'
    | '/plan'
    | '/practice'
    | '/ready'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/studio'
    | '/today'
    | '/topics'
    | '/tox'
    | '/warmup'
    | '/assess/post'
    | '/assess/pre'
    | '/assess/self'
    | '/learn/$id'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AssessRoute: typeof AssessRouteWithChildren
  BankRoute: typeof BankRoute
  BlueprintRoute: typeof BlueprintRoute
  CalculatorRoute: typeof CalculatorRoute
  CardsRoute: typeof CardsRoute
  CertificateRoute: typeof CertificateRoute
  ChallengeRoute: typeof ChallengeRoute
  CoachRoute: typeof CoachRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DomainsRoute: typeof DomainsRoute
  DrillRoute: typeof DrillRoute
  EligibilityRoute: typeof EligibilityRoute
  ErgoRoute: typeof ErgoRoute
  ErrorsRoute: typeof ErrorsRoute
  ExamRoute: typeof ExamRoute
  ExamDayRoute: typeof ExamDayRoute
  FlagsRoute: typeof FlagsRoute
  FormulasRoute: typeof FormulasRoute
  GamesRoute: typeof GamesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MathRoute: typeof MathRoute
  MockRoute: typeof MockRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PracticeRoute: typeof PracticeRoute
  ReadyRoute: typeof ReadyRoute
  RegisterRoute: typeof RegisterRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  TodayRoute: typeof TodayRoute
  TopicsRoute: typeof TopicsRoute
  ToxRoute: typeof ToxRoute
  WarmupRoute: typeof WarmupRoute
  LearnIdRoute: typeof LearnIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergo': {
      id: '/ergo'
      path: '/ergo'
      fullPath: '/ergo'
      preLoaderRoute: typeof ErgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-day': {
      id: '/exam-day'
      path: '/exam-day'
      fullPath: '/exam-day'
      preLoaderRoute: typeof ExamDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tox': {
      id: '/tox'
      path: '/tox'
      fullPath: '/tox'
      preLoaderRoute: typeof ToxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/post': {
      id: '/assess/post'
      path: '/post'
      fullPath: '/assess/post'
      preLoaderRoute: typeof AssessPostRouteImport
      parentRoute: typeof AssessRoute
    }
    '/assess/pre': {
      id: '/assess/pre'
      path: '/pre'
      fullPath: '/assess/pre'
      preLoaderRoute: typeof AssessPreRouteImport
      parentRoute: typeof AssessRoute
    }
    '/assess/self': {
      id: '/assess/self'
      path: '/self'
      fullPath: '/assess/self'
      preLoaderRoute: typeof AssessSelfRouteImport
      parentRoute: typeof AssessRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$id': {
      id: '/learn/$id'
      path: '/learn/$id'
      fullPath: '/learn/$id'
      preLoaderRoute: typeof LearnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessRouteChildren {
  AssessPostRoute: typeof AssessPostRoute
  AssessPreRoute: typeof AssessPreRoute
  AssessSelfRoute: typeof AssessSelfRoute
}

const AssessRouteChildren: AssessRouteChildren = {
  AssessPostRoute: AssessPostRoute,
  AssessPreRoute: AssessPreRoute,
  AssessSelfRoute: AssessSelfRoute,
}

const AssessRouteWithChildren =
  AssessRoute._addFileChildren(AssessRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AssessRoute: AssessRouteWithChildren,
  BankRoute: BankRoute,
  BlueprintRoute: BlueprintRoute,
  CalculatorRoute: CalculatorRoute,
  CardsRoute: CardsRoute,
  CertificateRoute: CertificateRoute,
  ChallengeRoute: ChallengeRoute,
  CoachRoute: CoachRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  DomainsRoute: DomainsRoute,
  DrillRoute: DrillRoute,
  EligibilityRoute: EligibilityRoute,
  ErgoRoute: ErgoRoute,
  ErrorsRoute: ErrorsRoute,
  ExamRoute: ExamRoute,
  ExamDayRoute: ExamDayRoute,
  FlagsRoute: FlagsRoute,
  FormulasRoute: FormulasRoute,
  GamesRoute: GamesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MathRoute: MathRoute,
  MockRoute: MockRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PracticeRoute: PracticeRoute,
  ReadyRoute: ReadyRoute,
  RegisterRoute: RegisterRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  TodayRoute: TodayRoute,
  TopicsRoute: TopicsRoute,
  ToxRoute: ToxRoute,
  WarmupRoute: WarmupRoute,
  LearnIdRoute: LearnIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
